# Site settings
title:       Lauro Caetano
email:       laurocaetano1@gmail.com
author:      Lauro Caetano
description: "About programming"
baseurl:     ""
url:         "http://laurocaetano.github.io"

# Google analytics
google_analytics: UA-64638719-1

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
show_social_icons: false
github_username: laurocaetano
stackoverflow_id:
twitter_username: laurocaetano
google_plus_id:
linkedin_username:
angellist_username:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: false
share_linkedin: true
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     kramdown
permalink:    pretty
paginate:     3
sass:
  compressed: true
